spring.application.name=passthru
passthru.base_timeout_secs=1
passthru.max_timeout_secs=86400

# Logging File Output https://docs.spring.io/spring-boot/reference/features/logging.html#features.logging.file-output
# If you are adding additional log files please add them to /var/log/ directory.
logging.file.name=/var/log/passthru.log